# Generated by Django 2.2.4 on 2019-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_key', models.IntegerField(blank=True, null=True)),
                ('catalog_no', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('catalog_price', models.FloatField(blank=True, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
