# Generated by Django 2.2.4 on 2019-08-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20190808_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Product Details', 'verbose_name_plural': 'Product Details'},
        ),
    ]
